DROP TABLE IF EXISTS Conversations;

CREATE TABLE IF NOT EXISTS Calender(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE IF NOT EXISTS JournalEntries(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gptmood TEXT NOT NULL,
    inputmood TEXT NOT NULL,
    JournalEntry TEXT NOT NULL,
    EntryDate TEXT NOT NULL
)